"""
/Energy-Battle-Remake/sys_tools_mod.py
System Tools Mod: In-battle admin tools reusing native ark menus.
This Mod is generated by Artificial Intelligence
"""

import noah
from noah import C
from actions.act_utils import able_forever, free_of_charge
from localize import Expression
from ark_menus import Menu_Setting, Menu_ModManager

# ==============================================================================
# 1. Localization Expressions (Fully localized, no raw attribute names, no emojis)
# ==============================================================================
SysToolsExpressions = {
    "zh_cn": {
        '/act/sys/name': f"{C['CYAN']}系统工具{C['RESET']}",
        '/act/sys/price': "0",
        '/act/sys/rule': f"{C['CYAN']}系统工具{C['RESET']} - {C['WHITE']}战时管理工具。支持查询战况、修改环境、热插拔模组与属性调整。{C['RESET']}",

        '/act/sys/title': f"\n{C['CYAN']}====== [系统工具] ======{C['RESET']}",
        '/act/sys/menu-1': "1. 高级战况与玩家数据查询",
        '/act/sys/menu-2': "2. 战时战场环境配置",
        '/act/sys/menu-3': "3. 战时模组管理",
        '/act/sys/menu-4': "4. 批量修改玩家属性",
        '/act/sys/menu-0': "0. 返回战斗",
        '/act/sys/prompt-opt': "请选择操作编号 > ",
        '/act/sys/exit': f"{C['YELLOW']}已退出系统工具。{C['RESET']}\n",
        '/act/sys/invalid-choice': f"{C['RED']}无效的选项。{C['RESET']}",

        '/act/sys/stt-title': f"\n{C['CYAN']}>>> [高级数据查询] 战场概况{C['RESET']}",
        '/act/sys/stt-summary': "存活总人数: $0 | 全场总能量: $1 | 地图垂直范围: [-$2 ~ $2]",
        '/act/sys/stt-pop-dist': "位置分布: $0",
        '/act/sys/stt-filter-prompt': "筛选队伍或位置 (例如 't1', 'p0'，留空显示全场) > ",
        '/act/sys/stt-press-enter': f"\n{C['GRAY']}[按回车键继续]{C['RESET']}",
        '/act/sys/stt-type-human': "人类",
        '/act/sys/stt-type-ai': "AI(Lv$0)",
        '/act/sys/stt-none': "无",
        '/act/sys/stt-header': "编号,类型,队伍,生命值,能量,位置,总伤害,击杀数,状态",

        '/act/sys/pl-title': f"\n{C['CYAN']}>>> [批量属性修改] 玩家数据控制{C['RESET']}",
        '/act/sys/pl-prompt-targets': "选择目标 (支持逗号隔开如 '1,3'; 或 'all' 全员; 或 't1' 选队伍; 'p0' 选层级) > ",
        '/act/sys/pl-target-count': "已命中 $0 名存活玩家。",
        '/act/sys/pl-prompt-attr': "请选择要修改的属性 (1.生命值 / 2.能量 / 3.位置 / 4.队伍 / 5.AI等级) > ",
        '/act/sys/attr-1': "生命值",
        '/act/sys/attr-2': "能量",
        '/act/sys/attr-3': "位置",
        '/act/sys/attr-4': "队伍",
        '/act/sys/attr-5': "AI等级",
        '/act/sys/pl-prompt-val': "请输入新的 $0 (支持相对加减如 '+5', '-2'; 直接输入为绝对赋值) > ",
        '/act/sys/pl-success': f"{C['GREEN']}成功批量修改了 $0 名玩家的「$1」。{C['RESET']}",
        '/act/sys/pl-err-no-target': f"{C['RED']}没有匹配到任何存活玩家。{C['RESET']}",
        '/act/sys/pl-err-attr': f"{C['RED']}无效的属性编号。{C['RESET']}",
        '/act/sys/pl-err-val': f"{C['RED']}数值解析错误。{C['RESET']}",
    },

    "en_us": {
        '/act/sys/name': f"{C['CYAN']}System Tools{C['RESET']}",
        '/act/sys/price': "0",
        '/act/sys/rule': f"{C['CYAN']}System Tools{C['RESET']} - {C['WHITE']}In-battle admin tools. Allows status query, config editing, mod management, and batch editing.{C['RESET']}",

        '/act/sys/title': f"\n{C['CYAN']}====== [System Tools] ======{C['RESET']}",
        '/act/sys/menu-1': "1. Advanced Battlefield & Player Status",
        '/act/sys/menu-2': "2. Configure Battlefield Environment",
        '/act/sys/menu-3': "3. In-battle Mod Manager",
        '/act/sys/menu-4': "4. Batch Edit Player Attributes",
        '/act/sys/menu-0': "0. Return to Battle",
        '/act/sys/prompt-opt': "Select an option > ",
        '/act/sys/exit': f"{C['YELLOW']}Exited System Tools.{C['RESET']}\n",
        '/act/sys/invalid-choice': f"{C['RED']}Invalid option.{C['RESET']}",

        '/act/sys/stt-title': f"\n{C['CYAN']}>>> [Advanced Query] Battlefield Overview{C['RESET']}",
        '/act/sys/stt-summary': "Alive: $0 | Total Energy: $1 | Map Levels: [-$2 ~ $2]",
        '/act/sys/stt-pop-dist': "Positions: $0",
        '/act/sys/stt-filter-prompt': "Filter by Team or Position (e.g. 't1', 'p0', empty for all) > ",
        '/act/sys/stt-press-enter': f"\n{C['GRAY']}[Press Enter to continue]{C['RESET']}",
        '/act/sys/stt-type-human': "Human",
        '/act/sys/stt-type-ai': "AI(Lv$0)",
        '/act/sys/stt-none': "None",
        '/act/sys/stt-header': "ID,Type,Team,Health,Energy,Pos,Damage,Kills,Status",

        '/act/sys/pl-title': f"\n{C['CYAN']}>>> [Batch Player Edit] Player Stat Control{C['RESET']}",
        '/act/sys/pl-prompt-targets': "Select targets (e.g. '1-5', '1,3,7-9', 'all', 't1' team, 'p0' level) > ",
        '/act/sys/pl-target-count': "$0 alive player(s) matched.",
        '/act/sys/pl-prompt-attr': "Select attribute to modify (1.Health / 2.Energy / 3.Position / 4.Team / 5.AI Level) > ",
        '/act/sys/attr-1': "Health",
        '/act/sys/attr-2': "Energy",
        '/act/sys/attr-3': "Position",
        '/act/sys/attr-4': "Team",
        '/act/sys/attr-5': "AI Level",
        '/act/sys/pl-prompt-val': "Enter new $0 (relative like '+5', '-2'; or absolute value) > ",
        '/act/sys/pl-success': f"{C['GREEN']}Successfully modified '$1' for $0 players.{C['RESET']}",
        '/act/sys/pl-err-no-target': f"{C['RED']}No alive players matched.{C['RESET']}",
        '/act/sys/pl-err-attr': f"{C['RED']}Invalid attribute selection.{C['RESET']}",
        '/act/sys/pl-err-val': f"{C['RED']}Value parsing error.{C['RESET']}",
    },

    "zh_tw": {
        '/act/sys/name': f"{C['CYAN']}系統工具{C['RESET']}",
        '/act/sys/price': "0",
        '/act/sys/rule': f"{C['CYAN']}系統工具{C['RESET']} - {C['WHITE']}戰時管理工具。支援查詢戰況、修改環境、熱插拔模組與屬性調整。{C['RESET']}",

        '/act/sys/title': f"\n{C['CYAN']}====== [系統工具] ======{C['RESET']}",
        '/act/sys/menu-1': "1. 高級戰況與玩家數據查詢",
        '/act/sys/menu-2': "2. 戰時戰場環境配置",
        '/act/sys/menu-3': "3. 戰時模組管理",
        '/act/sys/menu-4': "4. 批量修改玩家屬性",
        '/act/sys/menu-0': "0. 返回戰鬥",
        '/act/sys/prompt-opt': "請選擇操作編號 > ",
        '/act/sys/exit': f"{C['YELLOW']}已退出系統工具。{C['RESET']}\n",
        '/act/sys/invalid-choice': f"{C['RED']}無效的選項。{C['RESET']}",

        '/act/sys/stt-title': f"\n{C['CYAN']}>>> [高級數據查詢] 戰場概況{C['RESET']}",
        '/act/sys/stt-summary': "存活總人數: $0 | 全場總能量: $1 | 地圖垂直範圍: [-$2 ~ $2]",
        '/act/sys/stt-pop-dist': "位置分佈: $0",
        '/act/sys/stt-filter-prompt': "篩選隊伍或位置 (例如 't1', 'p0'，留空顯示全場) > ",
        '/act/sys/stt-press-enter': f"\n{C['GRAY']}[按Enter鍵繼續]{C['RESET']}",
        '/act/sys/stt-type-human': "人類",
        '/act/sys/stt-type-ai': "AI(Lv$0)",
        '/act/sys/stt-none': "無",
        '/act/sys/stt-header': "編號,類型,隊伍,生命值,能量,位置,總傷害,擊殺數,狀態",

        '/act/sys/pl-title': f"\n{C['CYAN']}>>> [批量屬性修改] 玩家數據控制{C['RESET']}",
        '/act/sys/pl-prompt-targets': "選擇目標 (支援逗號隔開如 '1,3'; 或 'all' 全員; 或 't1' 選隊伍; 'p0' 選層級) > ",
        '/act/sys/pl-target-count': "已命中 $0 名存活玩家。",
        '/act/sys/pl-prompt-attr': "請選擇要修改的屬性 (1.生命值 / 2.能量 / 3.位置 / 4.隊伍 / 5.AI等級) > ",
        '/act/sys/attr-1': "生命值",
        '/act/sys/attr-2': "能量",
        '/act/sys/attr-3': "位置",
        '/act/sys/attr-4': "隊伍",
        '/act/sys/attr-5': "AI等級",
        '/act/sys/pl-prompt-val': "請輸入新的 $0 (支援相對加減如 '+5', '-2'; 直接輸入為絕對賦值) > ",
        '/act/sys/pl-success': f"{C['GREEN']}成功批量修改了 $0 名玩家的「$1」。{C['RESET']}",
        '/act/sys/pl-err-no-target': f"{C['RED']}沒有匹配到任何存活玩家。{C['RESET']}",
        '/act/sys/pl-err-attr': f"{C['RED']}無效的屬性編號。{C['RESET']}",
        '/act/sys/pl-err-val': f"{C['RED']}數值解析錯誤。{C['RESET']}",
    },

    "ja_jp": {
        '/act/sys/name': f"{C['CYAN']}システムツール{C['RESET']}",
        '/act/sys/price': "0",
        '/act/sys/rule': f"{C['CYAN']}システムツール{C['RESET']} - {C['WHITE']}戦時管理ツール。一括データ照会、環境設定変更、MOD管理、能力値編集が可能です。{C['RESET']}",

        '/act/sys/title': f"\n{C['CYAN']}====== [システムツール] ======{C['RESET']}",
        '/act/sys/menu-1': "1. 高度な戦況・プレイヤー情報照会",
        '/act/sys/menu-2': "2. 戦場環境設定の変更",
        '/act/sys/menu-3': "3. 戦時MODマネージャー",
        '/act/sys/menu-4': "4. プレイヤー能力値の一括変更",
        '/act/sys/menu-0': "0. バトルに戻る",
        '/act/sys/prompt-opt': "操作を選択してください > ",
        '/act/sys/exit': f"{C['YELLOW']}システムツールを終了しました。{C['RESET']}\n",
        '/act/sys/invalid-choice': f"{C['RED']}無効な選択です。{C['RESET']}",

        '/act/sys/stt-title': f"\n{C['CYAN']}>>> [データ照会] 戦場概要{C['RESET']}",
        '/act/sys/stt-summary': "生存人数: $0 | 総エネルギー: $1 | マップ範囲: [-$2 ~ $2]",
        '/act/sys/stt-pop-dist': "位置分布: $0",
        '/act/sys/stt-filter-prompt': "チームまたは位置で絞り込み (例: 't1', 'p0'、空欄で全体) > ",
        '/act/sys/stt-press-enter': f"\n{C['GRAY']}[Enterキーで続行]{C['RESET']}",
        '/act/sys/stt-type-human': "人間",
        '/act/sys/stt-type-ai': "AI(Lv$0)",
        '/act/sys/stt-none': "なし",
        '/act/sys/stt-header': "ID,タイプ,チーム,体力,エネルギー,位置,ダメージ,キル数,状態",

        '/act/sys/pl-title': f"\n{C['CYAN']}>>> [能力値一括変更] プレイヤーデータ制御{C['RESET']}",
        '/act/sys/pl-prompt-targets': "対象を選択 (例 '1-5', '1,3', 全体 'all', チーム 't1', 階層 'p0') > ",
        '/act/sys/pl-target-count': "$0 人のプレイヤーが選択されました。",
        '/act/sys/pl-prompt-attr': "変更する属性を選択 (1.体力 / 2.エネルギー / 3.位置 / 4.チーム / 5.AIレベル) > ",
        '/act/sys/attr-1': "体力",
        '/act/sys/attr-2': "エネルギー",
        '/act/sys/attr-3': "位置",
        '/act/sys/attr-4': "チーム",
        '/act/sys/attr-5': "AIレベル",
        '/act/sys/pl-prompt-val': "新しい $0 を入力 ('+5', '-2' で相対変更、数値で直接設定) > ",
        '/act/sys/pl-success': f"{C['GREEN']}$0 人のプレイヤーの「$1」を正常に変更しました。{C['RESET']}",
        '/act/sys/pl-err-no-target': f"{C['RED']}該当するプレイヤーがいません。{C['RESET']}",
        '/act/sys/pl-err-attr': f"{C['RED']}無効な属性番号です。{C['RESET']}",
        '/act/sys/pl-err-val': f"{C['RED']}値の解析に失敗しました。{C['RESET']}",
    }
}

# Automatically inject expressions into the global localization table
for lang_key, exp_table in SysToolsExpressions.items():
    if lang_key in Expression:
        Expression[lang_key].update(exp_table)


# ==============================================================================
# 2. Target Parser
# ==============================================================================

def parse_target_players(input_str, core):
    """
    Parses user input into a unique list of existing, alive Player objects.
    Supports ranges ('1-5'), specific IDs ('1,3,7'), teams ('t1'), levels ('p0'), and 'all'.
    """
    raw_str = input_str.strip().lower()
    if not raw_str:
        return []

    if raw_str == "all":
        return list(core.PlDict.values())

    if raw_str.startswith("t") and raw_str[1:].isdigit():
        team_id = int(raw_str[1:])
        return [p for p in core.PlDict.values() if p.team == team_id]

    if raw_str.startswith("p"):
        pos_part = raw_str[1:]
        if pos_part.isdigit() or (pos_part.startswith('-') and pos_part[1:].isdigit()):
            pos_id = int(pos_part)
            return [p for p in core.PlDict.values() if p.place == pos_id]

    matched_ids = []
    tokens = [tk.strip() for tk in raw_str.split(",") if tk.strip()]

    for tk in tokens:
        # Range format logic
        if "-" in tk and not tk.startswith("-"):
            parts = tk.split("-")
            if len(parts) == 2:
                try:
                    start_id = int(parts[0].strip())
                    end_id = int(parts[1].strip())
                    low, high = min(start_id, end_id), max(start_id, end_id)
                    matched_ids.extend(range(low, high + 1))
                except ValueError:
                    continue
        else:
            try:
                matched_ids.append(int(tk))
            except ValueError:
                continue

    # Filter out non-existent players and eliminate duplicates
    seen = set()
    result = []
    for pid in matched_ids:
        if pid in core.PlDict and pid not in seen:
            seen.add(pid)
            result.append(core.PlDict[pid])

    return result


# ==============================================================================
# 3. Implementation Functions
# ==============================================================================

def handle_status(core):
    """Query advanced battlefield and player data."""
    core.ui.workdir = "/act/sys/"
    core.ui.out("./stt-title")

    total_alive = len(core.PlDict)
    total_energy = core.status.get("energy", {}).get("all", sum(p.energy for p in core.PlDict.values()))
    map_limit = core.BattleEnv.get("map", 3)
    core.ui.out("./stt-summary", imp=[total_alive, total_energy, map_limit])

    pop_stats = []
    for place, data in sorted(core.status.get("pop", {}).items(), key=lambda x: str(x[0])):
        if place != "all":
            pop_stats.append(f"{place}F: {len(data.get('sum', []))}")
    core.ui.out("./stt-pop-dist", imp=[", ".join(pop_stats)])

    filter_str = core.ui.inp("./stt-filter-prompt").strip().lower()

    # Retrieve localized header strings
    header_str = core.ui.get("./stt-header")
    header_tuple = tuple(header_str.split(","))
    table_data = [header_tuple]

    for p in core.PlDict.values():
        if filter_str.startswith("t") and filter_str[1:].isdigit():
            if p.team != int(filter_str[1:]): 
                continue
        elif filter_str.startswith("p") and (filter_str[1:].isdigit() or (filter_str[1:].startswith('-') and filter_str[2:].isdigit())):
            if p.place != int(filter_str[1:]): 
                continue

        p_type = core.ui.get("./stt-type-human") if p.real else noah.explain(core.ui.get("./stt-type-ai"), [p.ai_quality])
        stt_list = [k for k, v in p.status.items() if v]
        stt_str = ",".join(stt_list) if stt_list else core.ui.get("./stt-none")
        table_data.append((p.id, p_type, p.team, p.HP, p.energy, p.place, p.outd, len(p.kills), stt_str))

    table_format = f"{C['YELLOW']}$0{C['RESET']}\t$1\t{C['CYAN']}$2{C['RESET']}\t{C['GREEN']}$3{C['RESET']}\t{C['MAGENTA']}$4{C['RESET']}\t$5\t$6\t$7\t$8"
    core.ui.out(noah.table(table_data, table_format), directly=True)
    core.ui.inp("./stt-press-enter")


def handle_players(core):
    """Batch edit active player attributes with mapped localized names."""
    core.ui.workdir = "/act/sys/"
    core.ui.out("./pl-title")
    t_str = core.ui.inp("./pl-prompt-targets").strip()
    if not t_str: 
        return

    targets = parse_target_players(t_str, core)

    if not targets:
        core.ui.out("./pl-err-no-target")
        return

    core.ui.out("./pl-target-count", imp=[len(targets)])
    
    # Map numerical selection to internal attribute keys
    attr_map = {
        "1": "HP",
        "2": "energy",
        "3": "place",
        "4": "team",
        "5": "ai_quality"
    }

    attr_choice = core.ui.inp("./pl-prompt-attr").strip()
    if attr_choice not in attr_map:
        core.ui.out("./pl-err-attr")
        return

    internal_attr = attr_map[attr_choice]
    localized_attr_name = core.ui.get(f"./attr-{attr_choice}")

    val_str = core.ui.inp("./pl-prompt-val", imp=[localized_attr_name]).strip()
    if not val_str: 
        return

    success_count = 0
    for p in targets:
        cur_v = getattr(p, internal_attr, 0)
        try:
            if val_str.startswith("+") or val_str.startswith("-"):
                new_v = cur_v + int(val_str)
            else:
                new_v = int(val_str)
            setattr(p, internal_attr, new_v)
            success_count += 1
        except ValueError:
            core.ui.out("./pl-err-val")
            return

    # Update cache snapshot so AI and system logic immediately see the changes
    core.update_status()
    core.ui.out("./pl-success", imp=[success_count, localized_attr_name])


# ==============================================================================
# 4. Action Logic & Selection Hook
# ==============================================================================

def sys_selecting(pl, core, auto):
    """Main menu loop for System Tools."""
    org_delay = core.ui.typing_delay
    core.ui.typing_delay = 0
    core.ui.workdir = "/act/sys/"

    while True:
        core.ui.out([
            "./title",
            "./menu-1",
            "./menu-2",
            "./menu-3",
            "./menu-4",
            "./menu-0",
            "/share/endl"
        ])
        
        choice = core.ui.inp("./prompt-opt").strip()
        
        if choice == "1":
            handle_status(core)
        elif choice == "2":
            Menu_Setting(core.ui, core.BattleEnv, on_save=core.update_status)
            core.ui.workdir = "/act/sys/"
        elif choice == "3":
            lang = ModContents.get("chosen_lang_code", "zh_cn")
            Menu_ModManager(core.ui, core.Mods, lang, is_core=True, on_reload=core.ModsHotReload)
            core.ui.workdir = "/act/sys/"
        elif choice == "4":
            handle_players(core)
        elif choice == "0" or not choice:
            core.ui.out("./exit")
            break
        else:
            core.ui.out("./invalid-choice")

    core.ui.typing_delay = org_delay
    core.ls_acts()
    return (False, None)


ActionProperties = {
    "price": free_of_charge,
    "priority": 0,
    "able": able_forever,
    "human_only": True,
    "ai": [None],
    "weight": 0,
    "selecting_exec": sys_selecting,
    "dealing_exec": [],
}

# ==============================================================================
# 5. Mod Container Definition
# ==============================================================================

def SysToolsModReload():
    """Hook executed during kernel hot-reloads to refresh expressions."""
    lang = ModContents.get("chosen_lang_code", "zh_cn")
    if "ui" in ModContents and ModContents["ui"]:
        ModContents["ui"].exp.update(SysToolsExpressions.get(lang, {}))

ModContents = {
    "mod_name": "SysTool",
    "mod_priority": 5,
    "ActDict": {
        "sys": ActionProperties
    },
    "mod_reload": SysToolsModReload
}

